server:
  port: 8080

spring:
  application:
    name: XFService
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://1.95.60.219:3306/xfservice?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        namespace: public
        group: DEFAULT_GROUP
        shared-configs:
          - data-id: common.yml
            group: DEFAULT_GROUP
            refresh: true
        import-check:
          enabled: false

jwt:
  expiration: 3600
  secret: your-secret-key-here

logging:
  level:
    org.springframework.security: DEBUG
    com.xf.service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 